export const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
export const UPDATE_LIST_ITEM = 'UPDATE_LIST_ITEM';
export const REMOVE_LIST_ITEM = 'REMOVE_LIST_ITEM';
export const SAVE_STATE = 'SAVE_STATE';
export const REMOVE_STATE = 'REMOVE_STATE';
export const SET_LOGIN = 'SET_LOGIN';

export const FETCH_APP_PROPS_START = 'FETCH_APP_PROPS_START';
export const FETCH_APP_PROPS_SUCCESS = 'FETCH_APP_PROPS_SUCCESS';
export const FETCH_APP_PROPS_ERROR = 'FETCH_APP_PROPS_ERROR';

export const AUTH_USER_UPDATE = 'AUTH_USER_UPDATE';
export const AUTH_USER_REMOVE = 'AUTH_USER_REMOVE';

export const LOGIN = 'LOGIN';
export const SIGN_UP = 'SIGN_UP';
export const FORGOT_PASS = 'FORGOT_PASS';
export const RESET_PASS = 'RESET_PASS';
export const EMAIL_VERIFY = 'EMAIL_VERIFY';
export const MESSAGE = 'MESSAGE';
export const CLOSE_MODAL = 'CLOSE_MODAL';
