export const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
export const UPDATE_LIST_ITEM = 'UPDATE_LIST_ITEM';
export const REMOVE_LIST_ITEM = 'REMOVE_LIST_ITEM';

export const FETCH_APP_PROPS_START = 'FETCH_APP_PROPS_START';
export const FETCH_APP_PROPS_SUCCESS = 'FETCH_APP_PROPS_SUCCESS';
export const FETCH_APP_PROPS_ERROR = 'FETCH_APP_PROPS_ERROR';
